### ISSUE TITLE
about preprocessing

### ISSUE THREAD

**Issue by li143212** [gchaperon/neural-state-machine#1]
Hi,May I ask how to preprocess GQA dataset?And what is  "attrMap.json"?How can I get it?thx

**Comment by gchaperon** [comment]
hi, 
you can checkout what i have been doing here https://github.com/gchaperon/neural-state-machine/blob/main/nsm/datasets/gqa.py

this isn't official tho, for testing purposes i changed the preprocessing from the paper cause i still haven't tried generating scene graphs from images as described in the paper

that file contains the attributes in the concept vocabulary, i contacted the authors and they sent it to me

cheers,
gabriel

**Comment by li143212** [comment]
ok，i get it. Thaks a lot.

cheers,
li

**Comment by akkkb** [comment]
@gchaperon Could you please share the required *.json (attrMap.json, typeInfo.json, hObjInfo.json, relInfo.json) files for GQA preprocessing. You mentioned above that got from authors. 
It will be really helpful.

Thanks in advance.

**Comment by gchaperon** [comment]
hi, i didn't ask for permission to share those files. You should contact the authors, there is not much else i can do.

if you do, maybe CC me, if they allow me to share the files i could host them on my uni account.

**Comment by akkkb** [comment]
Thanks @gchaperon for response :) .
